/**
 * ImpostaSoggiornoConfigInterface.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.seda.payer.impostasoggiorno.webservice.configurazione.source;

public interface ImpostaSoggiornoConfigInterface extends java.rmi.Remote {
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaAnagraficaStrutturaResponse recuperaAnagraficaStruttura(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaAnagraficaStrutturaRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.AggiornaAnagraficaStrutturaResponse aggiornaAnagraficaStruttura(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.AggiornaAnagraficaStrutturaRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.InserisciAnagraficaStrutturaResponse inserisciAnagraficaStruttura(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.InserisciAnagraficaStrutturaRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.CancellaAnagraficaStrutturaResponse cancellaAnagraficaStruttura(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.CancellaAnagraficaStrutturaRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaListaAnagraficaStrutturaResponse recuperaListaAnagraficaStruttura(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaListaAnagraficaStrutturaRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaAnagraficaStrutturaCsvResponse recuperaAnagraficaStrutturaCsv(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaAnagraficaStrutturaCsvRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaAnagraficaStrutturaCatMerceologicaResponse recuperaAnagraficaStrutturaCatMerceologica(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaAnagraficaStrutturaCatMerceologicaRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaConfigurazioneImpostaSoggiornoResponse recuperaConfigurazioneImpostaSoggiorno(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaConfigurazioneImpostaSoggiornoRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaTipologiaStrutturaRicettivaResponse recuperaTipologiaStrutturaRicettiva(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaTipologiaStrutturaRicettivaRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.AggiornaTestataComunicazioneResponse aggiornaTestataComunicazione(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.AggiornaTestataComunicazioneRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaListaTipologiaStrutturaRicettivaResponse recuperaListaTipologiaStrutturaRicettiva(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaListaTipologiaStrutturaRicettivaRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.AggiornaTipologiaStrutturaRicettivaResponse aggiornaTipologiaStrutturaRicettiva(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.AggiornaTipologiaStrutturaRicettivaRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.InserisciTipologiaStrutturaRicettivaResponse inserisciTipologiaStrutturaRicettiva(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.InserisciTipologiaStrutturaRicettivaRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.CancellaTipologiaStrutturaRicettivaResponse cancellaTipologiaStrutturaRicettiva(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.CancellaTipologiaStrutturaRicettivaRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaTipologiaStrutturaRicettivaCsvResponse recuperaTipologiaStrutturaRicettivaCsv(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaTipologiaStrutturaRicettivaCsvRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaListaTipologiaSoggettoResponse recuperaListaTipologiaSoggetto(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaListaTipologiaSoggettoRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.AggiornaTipologiaSoggettoResponse aggiornaTipologiaSoggetto(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.AggiornaTipologiaSoggettoRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.InserisciTipologiaSoggettoResponse inserisciTipologiaSoggetto(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.InserisciTipologiaSoggettoRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.CancellaTipologiaSoggettoResponse cancellaTipologiaSoggetto(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.CancellaTipologiaSoggettoRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaTipologiaSoggettoResponse recuperaTipologiaSoggetto(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaTipologiaSoggettoRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaTipologiaSoggettiCsvResponse recuperaTipologiaSoggettiCsv(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaTipologiaSoggettiCsvRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.AggiornaAnagraficaStrutturaToHostResponse aggiornaAnagraficaStrutturaToHost(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.AggiornaAnagraficaStrutturaToHostRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaListaConfigurazioneImpSoggResponse recuperaListaConfigurazioneImpSogg(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaListaConfigurazioneImpSoggRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.AggiornaConfigurazioneImpSoggToHostResponse aggiornaConfigurazioneImpSoggToHost(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.AggiornaConfigurazioneImpSoggToHostRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.InserisciConfigurazioneImpSoggToHostResponse inserisciConfigurazioneImpSoggToHost(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.InserisciConfigurazioneImpSoggToHostRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.CancellaConfigurazioneImpSoggResponse cancellaConfigurazioneImpSogg(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.CancellaConfigurazioneImpSoggRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaListaEntiImpostaResponse recuperaListaEntiImposta(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaListaEntiImpostaRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.VerificaAnagraficaContribuentiResponse verificaAnagraficaContribuenti(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.VerificaAnagraficaContribuentiRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.AllineaPagamentiResponse allineaPagamenti(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.AllineaPagamentiRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.AllineaComunicazioniResponse allineaComunicazioni(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.AllineaComunicazioniRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaListaTariffaResponse recuperaListaTariffa(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaListaTariffaRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.AggiornaTariffaResponse aggiornaTariffa(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.AggiornaTariffaRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.InserisciTariffaResponse inserisciTariffa(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.InserisciTariffaRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.CancellaTariffaResponse cancellaTariffa(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.CancellaTariffaRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaTariffaResponse recuperaTariffa(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaTariffaRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.VerificaTariffaComunicazioniResponse verificaTariffaComunicazioni(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.VerificaTariffaComunicazioniRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaTariffeCsvResponse recuperaTariffeCsv(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaTariffeCsvRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
//inizio LP PG1800XX_016    
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaListaFasceTariffaResponse recuperaListaFasceTariffa(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaListaFasceTariffaRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaFasciaTariffaResponse recuperaFasciaTariffa(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaFasciaTariffaRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.InserisciFasciaTariffaResponse inserisciFasciaTariffa(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.InserisciFasciaTariffaRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.AggiornaFasciaTariffaResponse aggiornaFasciaTariffa(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.AggiornaFasciaTariffaRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.CancellaFasciaTariffaResponse cancellaFasciaTariffa(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.CancellaFasciaTariffaRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaFasceTariffeCsvResponse recuperaFasceTariffeCsv(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaFasceTariffeCsvRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
//fine LP PG1800XX_016    
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaListaComunicazioniResponse recuperaListaComunicazioni(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaListaComunicazioniRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaListaComunicazioniCsvResponse recuperaListaComunicazioniCsv(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaListaComunicazioniCsvRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.GetProgressivoComunicazioneResponse getProgressivoComunicazione(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.GetProgressivoComunicazioneRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaListaAnagraficheAlloggiPIvaResponse recuperaListaAnagraficheAlloggiPIva(com.seda.payer.impostasoggiorno.webservice.configurazione.dati.RecuperaListaAnagraficheAlloggiPIvaRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
}
