/**
 * ImpostaSoggiornoInterface.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.seda.payer.impostasoggiorno.webservice.wis.source;

public interface ImpostaSoggiornoInterface extends java.rmi.Remote {
    public com.seda.payer.impostasoggiorno.webservice.wis.dati.VerificaAutorizzazioneStrutturaResponse verificaAutorizzazioneStruttura(com.seda.payer.impostasoggiorno.webservice.wis.dati.VerificaAutorizzazioneStrutturaRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.wis.dati.SaveAnagraficaToHostResponse saveAnagraficaToHost(com.seda.payer.impostasoggiorno.webservice.wis.dati.SaveAnagraficaToHostRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.wis.dati.RecuperaListaTipologieStruttureResponse recuperaListaTipologieStrutture(com.seda.payer.impostasoggiorno.webservice.wis.dati.RecuperaListaTipologieStruttureRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.wis.dati.RecuperaListaTipologieSoggettiBelfResponse recuperaListaTipologieSoggettiBelf(com.seda.payer.impostasoggiorno.webservice.wis.dati.RecuperaListaTipologieSoggettiBelfRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.wis.dati.RecuperaTariffaImpostaSoggiornoStrutturaResponse recuperaTariffaImpostaSoggiornoStruttura(com.seda.payer.impostasoggiorno.webservice.wis.dati.RecuperaTariffaImpostaSoggiornoStrutturaRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.wis.dati.InserisciComunicazioneResponse inserisciComunicazione(com.seda.payer.impostasoggiorno.webservice.wis.dati.InserisciComunicazioneRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.wis.dati.AggiornaComunicazioneResponse aggiornaComunicazione(com.seda.payer.impostasoggiorno.webservice.wis.dati.AggiornaComunicazioneRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.wis.dati.RecuperaListaComunicazioniResponse recuperaListaComunicazioni(com.seda.payer.impostasoggiorno.webservice.wis.dati.RecuperaListaComunicazioniRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.wis.dati.VerificaAbilitazioneRIDHostResponse verificaAbilitazioneRIDHost(com.seda.payer.impostasoggiorno.webservice.wis.dati.VerificaAbilitazioneRIDHostRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.wis.dati.RecuperaDettaglioComunicazioneAggregatoResponse recuperaDettaglioComunicazioneAggregato(com.seda.payer.impostasoggiorno.webservice.wis.dati.RecuperaDettaglioComunicazioneAggregatoRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.wis.dati.StampaAvvisoComunicazionePdfResponse stampaAvvisoComunicazionePdf(com.seda.payer.impostasoggiorno.webservice.wis.dati.StampaAvvisoComunicazionePdfRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.wis.dati.SaveComunicazioneToHostResponse saveComunicazioneToHost(com.seda.payer.impostasoggiorno.webservice.wis.dati.SaveComunicazioneToHostRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.wis.dati.InserisciCompilazioneDiarioResponse inserisciCompilazioneDiario(com.seda.payer.impostasoggiorno.webservice.wis.dati.InserisciCompilazioneDiarioRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.wis.dati.AggiornaCompilazioneDiarioResponse aggiornaCompilazioneDiario(com.seda.payer.impostasoggiorno.webservice.wis.dati.AggiornaCompilazioneDiarioRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.wis.dati.EliminaCompilazioneDiarioResponse eliminaCompilazioneDiario(com.seda.payer.impostasoggiorno.webservice.wis.dati.EliminaCompilazioneDiarioRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.wis.dati.ControllaOverlayPeriodoDiarioResponse controllaOverlayPeriodoDiario(com.seda.payer.impostasoggiorno.webservice.wis.dati.ControllaOverlayPeriodoDiarioRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.wis.dati.RecuperaListaCompilazioniDiarioResponse recuperaListaCompilazioniDiario(com.seda.payer.impostasoggiorno.webservice.wis.dati.RecuperaListaCompilazioniDiarioRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.wis.dati.RecuperaDettagliAggregatiDiarioResponse recuperaDettagliAggregatiDiario(com.seda.payer.impostasoggiorno.webservice.wis.dati.RecuperaDettagliAggregatiDiarioRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.wis.dati.RecuperaDettaglioDiarioCompletoResponse recuperaDettaglioDiarioCompleto(com.seda.payer.impostasoggiorno.webservice.wis.dati.RecuperaDettaglioDiarioCompletoRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.wis.dati.RecuperaListaFasceTariffaResponse recuperaListaFasceTariffa(com.seda.payer.impostasoggiorno.webservice.wis.dati.RecuperaListaFasceTariffaRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.wis.dati.RecuperaListaComunicazioniSecondarieResponse recuperaListaComunicazioniSecondarie(com.seda.payer.impostasoggiorno.webservice.wis.dati.RecuperaListaComunicazioniSecondarieRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.wis.dati.ControllaComunicazioniSecondarieResponse controllaComunicazioniSecondarie(com.seda.payer.impostasoggiorno.webservice.wis.dati.ControllaComunicazioniSecondarieRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.wis.dati.GetDatiBollettinoResponse getDatiBollettino(com.seda.payer.impostasoggiorno.webservice.wis.dati.GetDatiBollettinoRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.wis.dati.GetBollettinoCumulativoResponse getBollettinoCumulativo(com.seda.payer.impostasoggiorno.webservice.wis.dati.GetBollettinoCumulativoRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.wis.dati.DdlAlloggiResponse getDdlAlloggi(com.seda.payer.impostasoggiorno.webservice.wis.dati.DdlAlloggiRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.wis.dati.RiepilogoImpostaSoggiornoResponse getRiepilogoIS(com.seda.payer.impostasoggiorno.webservice.wis.dati.RiepilogoImpostaSoggiornoRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.wis.dati.RecuperaListTariffeImpostaSoggiornoStrutturaResponse recuperaListTariffeImpostaSoggiornoStruttura(com.seda.payer.impostasoggiorno.webservice.wis.dati.RecuperaListTariffeImpostaSoggiornoStrutturaRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
    public com.seda.payer.impostasoggiorno.webservice.wis.dati.CheckComunicazioniBollettinoCumulativoResponse checkComunicazioniBollettinoCumulativo(com.seda.payer.impostasoggiorno.webservice.wis.dati.CheckComunicazioniBollettinoCumulativoRequest in) throws java.rmi.RemoteException, com.seda.payer.impostasoggiorno.webservice.srv.FaultType;
}
